# Generated by Django 3.1.3 on 2020-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='token_id',
            field=models.CharField(default='token_id', max_length=256),
            preserve_default=False,
        ),
    ]
