# Generated by Django 3.1.3 on 2020-11-17 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurant_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
