# Generated by Django 3.1.3 on 2020-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201117_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='token_id',
            field=models.CharField(default='No token id provided.', max_length=256),
        ),
    ]
