# Generated by Django 3.1.3 on 2020-11-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201117_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='password', max_length=256),
            preserve_default=False,
        ),
    ]
